import type { NextPage } from "next";
import Head from "next/head";
import { CategoriesPreviewList } from "../components/categories/CategoriesPreviewList";
import { Header } from "../components/Header/Header";

const categories = [
  "antiques",
  "bicycles",
  "books and comics",
  "clothes",
  "computers",
  "games and toys",
  "garden and yard",
  "home appliances",
  "music and music gear",
  "photo cameras",
  "shoes",
  "telephones",
  "tools and equipment",
  "watches",
];

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <CategoriesPreviewList categories={categories} />
    </>
  );
};

export default Home;
