import type { NextPage } from "next";
import Head from "next/head";
import { CategoriesPreviewList } from "../components/Categories/CategoriesPreviewList";
import { SearchBox } from "../components/SearchBox/SearchBox";
import { categories } from "../utils/categories";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>E-Flea</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBox />
      <CategoriesPreviewList categories={categories} />
    </>
  );
};

export default Home;
