export const categories = {
  antiques: [
    "candlesticks, vases and ashtrays",
    "chandeliers and lamps",
    "dishes and cutlery",
    "jewelry",
    "toys",
    "watches",
    "other",
  ],

  bicycles: [
    "bmx",
    "children's bicycles and scooters",
    "electric bicycles",
    "mountainbike",
    "vintage",
    "other",
  ],

  books: [
    "books for children",
    "comics",
    "cookbook",
    "encyclopedias and atlases",
    "history",
    "horror",
    "philosophy and sociology",
    "poetry",
    "religion and mythology",
    "thriller",
    "other",
  ],

  cameras: [
    "analog cameras",
    "video cameras",
    "digital cameras",
    "drones",
    "go pros",
    "objectives and lenses",
    "photo films",
    "polaroid cameras",
    "other",
  ],

  "clothes (children)": [
    "jackets",
    "jeans",
    "hoodies",
    "pants",
    "shorts",
    "sweaters",
    "tracksuits",
    "t-shirts",
    "other",
  ],

  "clothes (men)": [
    "coats",
    "jackets",
    "jeans",
    "hoodies",
    "pants",
    "shorts",
    "suits",
    "sweaters",
    "tracksuits",
    "t-shirts",
    "other",
  ],

  "clothes (woman)": [
    "blouses",
    "dresses",
    "fur coats",
    "jackets",
    "jeans",
    "leggings",
    "skirts",
    "nightgowns",
    "tracksuits",
    "t-shirts",
    "other",
  ],

  computers: [
    "batteries",
    "chargers",
    "desktop",
    "external hard drives",
    "keyboards",
    "laptops",
    "monitors",
    "mouses",
    "printers",
    "tablets",
    "web cameras",
    "other",
  ],

  furniture: [
    "armchairs",
    "beds",
    "chairs",
    "closets",
    "couches",
    "showcases",
    "tables",
    "other",
  ],

  "games and toys": [
    "action figures",
    "board games",
    "dolls",
    "puzzle",
    "stuffed toys",
  ],

  "garden and yard": [
    "backyard barbecue",
    "lawn mowers and trimmers",
    "pots and planters",
    "swimming pools",
    "other",
  ],

  "household decor": [
    "bedclothes and pillows",
    "carpets",
    "cezves and teapots",
    "chandeliers and ceiling lights",
    "curtains and blinds",
    "decoration for celebrations",
    "mirrors",
    "pots and pans",
    "silverware and cutlery",
    "other",
  ],

  "music gear and instruments": [
    "audio equipment",
    "bass guitars",
    "cables",
    "drums",
    "guitars",
    "keyboards",
    "pianos",
    "sound systems",
    "stage lighting",
    "strings",
    "wind instruments",
    "other",
  ],

  "shoes (children)": ["boots", "sandals", "slippers", "sneakers"],

  "shoes (men)": ["boots", "sandals", "shoes", "slippers", "sneakers"],

  "shoes (woman)": [
    "boots",
    "sandals",
    "shoes",
    "slippers",
    "sneakers",
    "other",
  ],

  telephones: [
    "honor",
    "huawei",
    "iphone",
    "lenovo",
    "lg",
    "nokia",
    "samsung",
    "sony",
    "xiaomi",
    "other",
  ],

  "tools and equipment": [
    "carpentry tools",
    "chainsaws",
    "drills",
    "grinders",
    "hammers",
    "hand tool sets",
    "pliers",
    "welding tool",
    "other",
  ],

  "watches and jewelry": [
    "badges",
    "bracelets",
    "earrings",
    "necklaces",
    "rings",
    "wristwatch",
  ],
  other: [],
};
